-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
#                                  FROM REST_INFO
#                                  GROUP BY FOOD_TYPE)
# ORDER BY FOOD_TYPE DESC;

SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES 
FROM REST_INFO AS I
WHERE I.FAVORITES = (SELECT MAX(II.FAVORITES) 
                     FROM REST_INFO AS II
                     WHERE II.FOOD_TYPE = I.FOOD_TYPE)
ORDER BY I.FOOD_TYPE DESC;