# -- 코드를 입력하세요
# SELECT i.REST_ID, i.REST_NAME,i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO AS i
# INNER JOIN REST_REVIEW AS r ON i.REST_ID = r.REST_ID
# WHERE i.ADDRESS LIKE '서울%'
# GROUP BY i.REST_ID 
# ORDER BY SCORE DESC, i.FAVORITES DESC;







SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW AS R 
LEFT JOIN REST_INFO AS I ON R.REST_ID = I.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
ORDER BY ROUND(AVG(R.REVIEW_SCORE), 2) DESC , I.FAVORITES DESC

















