SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(S.USER_ID)) AS USERS
FROM ONLINE_SALE AS S
JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID
GROUP BY YEAR, MONTH, GENDER HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER ASC