SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*)
                             FROM USER_INFO
                             WHERE YEAR(USER_INFO.JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS S
LEFT JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID
WHERE YEAR(I.JOINED) = '2021'
GROUP BY DATE_FORMAT(S.SALES_DATE, '%Y-%m')
ORDER BY YEAR ASC, MONTH ASC;

# SELECT COUNT(*)
#                              FROM USER_INFO
#                              WHERE YEAR(USER_INFO.JOINED) = '2021'