-- 코드를 작성해주세요
# SELECT ITEM_TREE.PARENT_ITEM_ID
# FROM ITEM_INFO 
# JOIN ITEM_TREE ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
# WHERE RARITY = 'RARE';


SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_TREE.ITEM_ID
                  FROM ITEM_TREE
                  WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID
                                           FROM ITEM_INFO
                                           WHERE RARITY = 'RARE'))
ORDER BY ITEM_ID DESC;

