-- 코드를 작성해주세요
SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES AS E
LEFT JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY ROUND(AVG(E.SAL)) DESC 