SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (SELECT B.BOARD_ID
                  FROM USED_GOODS_BOARD AS B
                  ORDER BY B.VIEWS DESC
                  LIMIT 1)
ORDER BY FILE_PATH DESC;
