SELECT b.CATEGORY, SUM(s.SALES) AS TOTAL_SALES
FROM BOOK AS b
INNER JOIN BOOK_SALES AS s ON b.BOOK_ID = s.BOOK_ID
WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;