# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE PRICE IN (SELECT MAX(PRICE)
#                 FROM FOOD_PRODUCT
#                 GROUP BY CATEGORY)
#       AND CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY PRICE DESC

SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
WHERE F.PRICE = (SELECT MAX(FF.PRICE)
                 FROM FOOD_PRODUCT AS FF
                 WHERE FF.CATEGORY = F.CATEGORY
                )
      AND F.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY F.PRICE DESC