SET @PRICE = -10000;
# SELECT (@PRICE := @PRICE + 10000) AS PRICE_GROUP, (SELECT COUNT(*)
#                                                    FROM PRODUCT
#                                                    WHERE PRICE BETWEEN @PRICE AND @PRICE + 9999) AS PRODUCTS
# FROM PRODUCT 
SELECT TRUNCATE(PRICE / 10000, 0) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY  TRUNCATE(PRICE / 10000, 0) HAVING COUNT(*) > 0
ORDER BY PRICE_GROUP ASC;